import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    imgUrl: "https://therightfit.netlify.app/assets/shoes.jpg",
    isTrending: false,
    isFavourite: false,
    title: "Nike",
    productCategory: "Men Sneakers",
    newPrice: 750,
    oldPrice: 2499,
    discount: 70,
    outOfStock: false,
    isFast: true,
    itemCategory: "men",
    itemRating: 4.8
  },
  {
    _id: uuid(),
    imgUrl:
      "https://rukminim2.flixcart.com/image/332/398/kthjy4w0/shoe/h/h/x/5-gug87-adidas-cblack-clelil-ftwwht-original-imag6tgyzy3tjf5v.jpeg?q=50",
    isTrending: true,
    isFavourite: false,
    title: "Adidas",
    productCategory: "Women Shoes",
    newPrice: 750,
    oldPrice: 1499,
    discount: 50,
    outOfStock: true,
    isFast: true,
    itemCategory: "women",
    itemRating: 3.9
  },
  {
    _id: uuid(),
    imgUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Nikko_black_sandal.jpg/800px-Nikko_black_sandal.jpg",
    isTrending: false,
    isFavourite: false,
    title: "Bata",
    productCategory: "Boys Sandals",
    newPrice: 3159,
    oldPrice: 3999,
    discount: 21,
    outOfStock: false,
    isFast: false,
    itemCategory: "boys",
    itemRating: 2.9
  },
  {
    _id: uuid(),
    imgUrl: "https://rukminim2.flixcart.com/image/714/857/jr83gy80/shoe/t/s/k/sx0131l-5-sparx-pinkblack-original-imafd2hgbs5dbpvx.jpeg?q=50",
    isTrending: true,
    isFavourite: false,
    title: "Sparx",
    productCategory: "Women Running Shoes - Premium",
    newPrice: 2554,
    oldPrice: 3499,
    discount: 27,
    outOfStock: false,
    isFast: true,
    itemCategory: "women",
    itemRating: 1.1
  },
  {
    _id: uuid(),
    imgUrl: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/1f64924b-0da5-49fd-857a-533684e27b96/blazer-mid-77-little-kids-shoes-Bnnf4k.png",
    isTrending: false,
    isFavourite: false,
    title: "Nike",
    productCategory: "Girls Shoes - Premium",
    newPrice: 1574,
    oldPrice: 2499,
    discount: 37,
    outOfStock: true,
    isFast: false,
    itemCategory: "girls",
    itemRating: 1.8
  },
  {
    _id: uuid(),
    imgUrl:
      "https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dw72da6744/images/a_08/A01735C_A_08X1.jpg?sw=406",
    isTrending: true,
    isFavourite: false,
    title: "All Star",
    productCategory: "Boys Converse",
    newPrice: 1674,
    oldPrice: 2499,
    discount: 33,
    outOfStock: false,
    isFast: true,
    itemCategory: "boys",
    itemRating: 2.5
  },
  {
    _id: uuid(),
    imgUrl:
      "https://cdn.lifestyleasia.com/wp-content/uploads/2019/08/20153351/6e03e37670a9089e01e24eeddc9eee8b.jpeg",
    isTrending: false,
    isFavourite: false,
    title: "Addidas Collection",
    productCategory: "Addidas Vintage for Men",
    newPrice: 494,
    oldPrice: 1499,
    discount: 67,
    outOfStock: false,
    isFast: false,
    itemCategory: "men",
    itemRating: 3.6
  },
  {
    _id: uuid(),
    imgUrl: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/81863d87-25de-4521-a419-6258ac8f5742/flex-experience-run-10-road-running-shoes-dw002X.png",
    isTrending: false,
    isFavourite: false,
    title: "Nike",
    productCategory: "Girls Running Shoes",
    newPrice: 1644,
    oldPrice: 3499,
    discount: 53,
    outOfStock: true,
    isFast: true,
    itemCategory: "girls",
    itemRating: 4.2
  },
  {
    _id: uuid(),
    imgUrl: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/193257/01/sv01/fnd/IND/fmt/png/Enzo-2-Metal-Women's-Running-Shoes",
    isTrending: true,
    isFavourite: false,
    title: "Puma",
    productCategory: "Women Running Shoes",
    newPrice: 899,
    oldPrice: 4499,
    discount: 80,
    outOfStock: false,
    isFast: false,
    itemCategory: "women",
    itemRating: 4.5
  },
  {
    _id: uuid(),
    imgUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    isTrending: true,
    isFavourite: false,
    title: "Nike Collection",
    productCategory: "Men Running Shoes",
    newPrice: 1644,
    oldPrice: 3499,
    discount: 53,
    outOfStock: false,
    isFast: false,
    itemCategory: "men",
    itemRating: 4.7
  },
  {
    _id: uuid(),
    imgUrl: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    isTrending: true,
    isFavourite: false,
    title: "Nike Sneaker Collection",
    productCategory: "Women Sneakers",
    newPrice: 1674,
    oldPrice: 2499,
    discount: 33,
    outOfStock: false,
    isFast: false,
    itemCategory: "women",
    itemRating: 4.5
  },
  {
    _id: uuid(),
    imgUrl: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
    isTrending: true,
    isFavourite: false,
    title: "Bata Collection",
    productCategory: "Women Heels",
    newPrice: 899,
    oldPrice: 4499,
    discount: 80,
    outOfStock: false,
    isFast: false,
    itemCategory: "women",
    itemRating: 4.0
  },
  {
    _id: uuid(),
    imgUrl: "https://images.unsplash.com/photo-1595341888016-a392ef81b7de?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1179&q=80",
    isTrending: true,
    isFavourite: false,
    title: "K-SWiss",
    productCategory: "Men Sneakers",
    newPrice: 3159,
    oldPrice: 3999,
    discount: 21,
    outOfStock: false,
    isFast: true,
    itemCategory: "men",
    itemRating: 4.9
  },
  {
    _id: uuid(),
    imgUrl: "https://images.unsplash.com/photo-1518049362265-d5b2a6467637?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=449&q=80",
    isTrending: true,
    isFavourite: false,
    title: "The Wedding Collection",
    productCategory: "Women Heels",
    newPrice: 494,
    oldPrice: 1499,
    discount: 67,
    outOfStock: false,
    isFast: false,
    itemCategory: "women",
    itemRating: 4.5
  },
  // from here
  {
    _id: uuid(),
    imgUrl: "https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1112&q=80",
    isTrending: true,
    isFavourite: false,
    title: "NX-90 Collection",
    productCategory: "Men Sneakers",
    newPrice: 3600,
    oldPrice: 4499,
    discount: 20,
    outOfStock: false,
    isFast: true,
    itemCategory: "men",
    itemRating: 4.5
  },
  {
    _id: uuid(),
    imgUrl: "https://cdn.pixabay.com/photo/2018/12/17/23/39/baby-shoes-3881526_960_720.jpg",
    isTrending: true,
    isFavourite: false,
    title: "Eeneral",
    productCategory: "Boys Boots",
    newPrice: 899,
    oldPrice: 4499,
    discount: 80,
    outOfStock: false,
    isFast: false,
    itemCategory: "boys",
    itemRating: 4.5
  },
  {
    _id: uuid(),
    imgUrl: "https://cdn.pixabay.com/photo/2017/06/15/15/55/rainbow-colors-2405766_960_720.jpg",
    isTrending: true,
    isFavourite: false,
    title: "The Girls Store",
    productCategory: "Girls Shoes",
    newPrice: 3600,
    oldPrice: 4499,
    discount: 20,
    outOfStock: false,
    isFast: false,
    itemCategory: "girls",
    itemRating: 4.5
  },
  {
    _id: uuid(),
    imgUrl: "https://cdn.pixabay.com/photo/2018/01/23/18/21/winter-shoes-3102060_960_720.jpg",
    isTrending: true,
    isFavourite: false,
    title: "Bata Collection",
    productCategory: "Girls Winter Shoes",
    newPrice: 494,
    oldPrice: 1499,
    discount: 67,
    outOfStock: false,
    isFast: false,
    itemCategory: "girls",
    itemRating: 4.5
  },
  {
    _id: uuid(),
    imgUrl: "https://cdn.pixabay.com/photo/2018/01/24/21/31/childrens-shoes-3104832_960_720.jpg",
    isTrending: true,
    isFavourite: false,
    title: "Bata Collection",
    productCategory: "Girls Shoes",
    newPrice: 3159,
    oldPrice: 3999,
    discount: 21,
    outOfStock: false,
    isFast: false,
    itemCategory: "girls",
    itemRating: 4.5
  },
  {
    _id: uuid(),
    imgUrl: "https://cdn.pixabay.com/photo/2017/12/23/10/56/childrens-shoes-3035034_960_720.jpg",
    isTrending: true,
    isFavourite: false,
    title: "The Boys Store",
    productCategory: "Boys Shoes",
    newPrice: 494,
    oldPrice: 1499,
    discount: 67,
    outOfStock: false,
    isFast: false,
    itemCategory: "boys",
    itemRating: 4.9
  },
  {
    _id: uuid(),
    imgUrl: "https://cdn.pixabay.com/photo/2019/08/10/16/04/baby-shoes-4397235__340.jpg",
    isTrending: true,
    isFavourite: false,
    title: "Bata Collection",
    productCategory: "Girls Shoes",
    newPrice: 494,
    oldPrice: 1499,
    discount: 67,
    outOfStock: false,
    isFast: false,
    itemCategory: "girls",
    itemRating: 4.5
  },
  {
    _id: uuid(),
    imgUrl: "https://cdn.pixabay.com/photo/2014/02/15/19/27/shoes-266849__340.jpg",
    isTrending: true,
    isFavourite: false,
    title: "The Boys Store",
    productCategory: "Boys Shoes",
    newPrice: 3159,
    oldPrice: 3999,
    discount: 21,
    outOfStock: false,
    isFast: true,
    itemCategory: "boys",
    itemRating: 3.0
  },
  {
    _id: uuid(),
    imgUrl: "https://images.unsplash.com/photo-1562183241-b937e95585b6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=465&q=80",
    isTrending: true,
    isFavourite: false,
    title: "Addidas Collection",
    productCategory: "Mens Running Shoes",
    newPrice: 494,
    oldPrice: 1499,
    discount: 67,
    outOfStock: false,
    isFast: false,
    itemCategory: "men",
    itemRating: 2.5
  },
  {
    _id: uuid(),
    imgUrl: "https://images.unsplash.com/photo-1601924638867-3a6de6b7a500?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    isTrending: true,
    isFavourite: false,
    title: "The Wild Collection",
    productCategory: "Women Heels",
    newPrice: 750,
    oldPrice: 1499,
    discount: 50,
    outOfStock: true,
    isFast: false,
    itemCategory: "women",
    itemRating: 3.9
  },
  {
    _id: uuid(),
    imgUrl: "https://images.unsplash.com/photo-1602033693387-3531914e7185?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzN8fHNob2VzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    isTrending: true,
    isFavourite: false,
    title: "Nike Collection",
    productCategory: "Men Sneakers",
    newPrice: 750,
    oldPrice: 2499,
    discount: 70,
    outOfStock: true,
    isFast: false,
    itemCategory: "men",
    itemRating: 3.5
  }
  
];
